/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project1;

/**
 *
 * @author Kwanele
 */
public class aboutUs extends javax.swing.JFrame {

    /**
     * Creates new form aboutUs
     */
    private PlayBoard playBoard; // Add a reference to the PlayBoard frame
    public aboutUs(PlayBoard playBoard) {
        initComponents();
        setFixedSize();
        this.playBoard = playBoard; // Initialize the reference
    }

    private aboutUs() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void setFixedSize() { // this method fixes the size of the frame upon running the file
        setSize(900, 600);  // Set the desired size(setSize)
        setResizable(false);  // Prevent resizing by the user
        setLocationRelativeTo(null); // sets the loaction of the frame to the centre
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><u>ABOUT US</u></html>");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html> <h2>About - Card Clash</h2> <p> \n    Welcome to Card Clash, created by Kwanele Sishi and Sicelo Thusi. We are passionate about game development and have put our hearts and minds into crafting this exciting card game for you. We believe that games have the power to bring people together and challenge their skills. With Card Clash, we hope to offer you countless hours of entertainment and a chance to outsmart your digital opponent. Thank you for choosing to play our game, and we hope you have a fantastic time exploring the world of Card Clash!\n</p><p> <h2>Our Mission</h2> Our mission is clear: to provide players with a captivating and engaging card game that challenges their skills, sharpens their strategic thinking, and, most importantly, offers hours of pure entertainment. Our goal is to provide you with a fun and strategic gaming experience that you can enjoy alone or with friends. We believe that gaming should be more than just a pastime; it should be an experience that leaves players exhilarated and eager for more. <br> <h2>Why Card Clash?</h2> What sets Card Clash apart is its commitment to delivering an experience that combines the thrill of competition with the joy of strategic gameplay. We wanted to create a game that is accessible to everyone, from seasoned card players to those new to the world of gaming. Card Clash is designed to be easy to pick up and play, yet it offers endless possibilities for players to develop their own winning strategies <br> Thank you for being a part of the Card Clash community. Let's embark on this adventure of cards, strategy, and endless fun together!. </html>  ");

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        jLabel2.getAccessibleContext().setAccessibleName("About - Card Clash\nWelcome to the world of Card Clash! We are a passionate team of game developers who share a common goal: to create immersive, exciting, and strategic gaming experiences. Our journey began with a simple idea – to bring the thrill of card battles to players around the world, right from the comfort of their devices.\n\nOur Purpose\nOur Purpose is clear: to provide players with a captivating and engaging card game that challenges their skills, sharpens their strategic thinking, and, most importantly, offers hours of pure entertainment. We believe that gaming should be more than just a pastime; it should be an experience that leaves players exhilarated and eager for more. \nWhy Card Clash?\nWhat sets Card Clash apart is its commitment to delivering an experience that combines the thrill of competition with the joy of strategic gameplay. We wanted to create a game that is accessible to everyone, from seasoned card players to those new to the world of gaming. Card Clash is designed to be easy to pick up and play, yet it offers endless possibilities for players to develop their own winning strategies. \n");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    // Hide the aboutUs frame
    setVisible(false);

    // Show the PlayBoard frame using the reference
    playBoard.setVisible(true);

    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
          backBtn.setBackground(new java.awt.Color(255,0,153)); // Changes to the desired color
        backBtn.setForeground(new java.awt.Color(0,0,0)); // Changes to the desired text color
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
         backBtn.setBackground(new java.awt.Color(0,0,0)); // Changes to the desired color
        backBtn.setForeground(new java.awt.Color(255,0,153)); // Changes to the desired text color
    }//GEN-LAST:event_backBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new aboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
